### ISSUE TITLE
how to use this in Android Studio using CMAKE?

### ISSUE THREAD

**Issue by d-fal** [tuarua/FFmpeg-for-Android-Prebuilt#1]
I need to use these libraries in android studio with CMAKE. I store the libs folder in src/main/jniLibs and also targeted include files in CMAKE. But, when I run the project I get some errors. Can anyone help?

**Comment by tuarua** [comment]
These prebuilt binaries are the support files for this:

https://github.com/tuarua/LibAVANE-Android-Example
